[platformio]
default_envs = linbridge-2_0-scaffold

[env:linbridge-2_0-scaffold]
platform = platformio/espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
build_unflags =
    -std=gnu++11
